import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

import { Layout } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme accentColor="blue">
          <Layout>{children}</Layout>
        </Theme>
      </body>
    </html>
  )
}
